apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-checkout
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-checkout
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
    {{- if .Values.debug.enabled }}
    - name: inspector
      port: {{ .Values.debug.port }}
      targetPort: {{ .Values.debug.port }}
    {{- end }}
